<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 /Users/mr-josh/Documents/mr-josh/flowers/static/models/flower.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from "three";
  import { Group, MeshToonMaterial } from "three";
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from "@threlte/core";
  import { useGltf } from "@threlte/extras";

  type $$Props = Props<THREE.Group> & { opacity?: number, color?: number };
  type $$Events = Events<THREE.Group>;
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

  export const ref = new Group();
  export let opacity: number = 1;
  export let color: number = 0;

  type GLTFResult = {
    nodes: {
      FlowerFace: THREE.Mesh;
      FlowerFace_1: THREE.Mesh;
      Stalk: THREE.Mesh;
    };
    materials: {
      Base: THREE.MeshStandardMaterial;
      Petals: THREE.MeshStandardMaterial;
      Stalk: THREE.MeshStandardMaterial;
    };
  };

  const gltf = useGltf<GLTFResult>("/models/flower.glb");

  const component = forwardEventHandlers();

  const faceMaterial = new MeshToonMaterial({ color: `hsl(${color}, 50%, 70%)`, opacity, transparent: true });
  const petalMaterial = new MeshToonMaterial({ color: `hsl(${color - 10}, 60%, 85%)`, opacity, transparent: true });
  const stalkMaterial = new MeshToonMaterial({ color: 0x228b22, opacity, transparent: true });

  $: faceMaterial.opacity = opacity;
  $: petalMaterial.opacity = opacity;
  $: stalkMaterial.opacity = opacity;
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={0.5}>
      <T.Group position={[0, 1.2, 0]} rotation={[0.7, 0, 0]}>
        <T.Mesh geometry={gltf.nodes.FlowerFace.geometry} material={faceMaterial} />
        <T.Mesh geometry={gltf.nodes.FlowerFace_1.geometry} material={petalMaterial} />
      </T.Group>
      <T.Mesh geometry={gltf.nodes.Stalk.geometry} material={stalkMaterial} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
